### PR TITLE
chore: add analytics

### PR DESCRIPTION
**Pull request by olizilla**
It'd be nice to know if folks are reading the docs, and if so, how far they get.

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by hsanjuan** [comment]
I don't like user tracking and analytics. Honestly I wish we had an alternative to sending our user data to Google. Not even in the websites of a distributed privacy-aware technology can be browsed without putting the ad-blocker condom on... And we have no one assigned to making something useful out of this data at the moment. So I can live without this, but I'm flexible and I don't mind so much in the end.

That said, implentation is better using Hugo's provided template for this. See:

https://gohugo.io/templates/internal/

:)

**Comment by olizilla** [comment]
I hear you. I am working on a self-hosted solution: https://github.com/ipfs-shipyard/ipfs-webui/pull/930

@mikeal is working on making good use of the data as part our effort to have better metrics for the IPFS project https://github.com/protocol/metrics/issues/1

To alivate the unplesant feeling in the meantime, I can wrap the script in a check for the users `navigator.doNotTrack` setting, so we don't fetch anything from google if it is set.

> hat said, implentation is better using Hugo's provided template for this. See:

I'm aware of the internal template, but the template suggested by GA differs significantly. I'd like to manage it ourselves.

**Comment by hsanjuan** [comment]
afaik, google respects DNT (?). It's ok. Thanks man!

**Comment by Stebalien** [comment]
IIRC, google ignores it completely.

**Pull request merged**
