### PR TITLE
Implement toggle feature for left nav

### LINKED ISSUE #91: Implement toggle feature for left nav
Right now it is impossible for the user to toggle from parent to child nav without being redirected to the parent that they click on. 

Goal is to make it so that users can collapse a nav without changing the page that they are on.

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fix https://github.com/ipfs/ipfs-cluster-website/issues/91.

### CODE REVIEW

**Comment by meiqimichelle** [comment]
Hi @tapaswenipathak ! Thank you for the contribution! I pulled your branch down and tested it locally, and I'm not sure I see where your change is implemented. I think you may have worked off `master` instead of the `new-docs-layout` branch. I might be misunderstanding though -- could you add a screenshot of your change in action? Thank you again!

**Comment by tapaswenipathak** [comment]
Hello @meiqimichelle: I didn't know `new-docs-layout` branch exist, rebasing and merging. From the ticket comment I don't think toggle feature is implemented. I just looked at the `new-docs-layout` branch, correct me if I'm wrong.

**Comment by meiqimichelle** [comment]
Ah, sorry for the confusion! Your contribution came just as I was iterating on the layout, and removing the need for a toggle to simplify everything. I'll open a WIP PR so it's a little clearer what's in progress! :-/

**Comment by tapaswenipathak** [comment]
Should I close this PR?

**Comment by tapaswenipathak** [comment]
From https://github.com/ipfs/ipfs-cluster-website/issues/91#issuecomment-516192813: should I close this PR?

**Comment by tapaswenipathak** [comment]
Hey @meiqimichelle! Can you let me know if you are done with implementing the feature, I can then close the PR.

**Pull request closed without merging**
