### PR TITLE
increase font-weight to 400 for ul and p

### PR DESCRIPTION
**Pull request by kyledrake**
I believe this will improve the readability of the site. I wasn't able to test on all subsections because the `make` command was not making all the pages (they were returning 404s) and the front site looked different than it does in production, not sure why.

### CODE REVIEW

**Comment by kyledrake** [comment]
https://github.com/ipfs/ipfs-cluster-website/issues/25#issuecomment-415763376

**Comment by hsanjuan** [comment]
Thanks, but I'd prefer to do a general readability revamp overviewed by @akrych, which is likely going to involve more than this.

**Comment by hsanjuan** [comment]
Actually, I'll let her decide if this is good :)

**Comment by kyledrake** [comment]
@akrych Can you review this PR please? Thank you.

**Review by akrych — COMMENTED** [review]
Looks good, for now ;)

**Comment by akrych** [comment]
@kyledrake hmm take a look here, if I don't broke anything? :/

**Pull request merged**
