### PR TITLE
Fix site so it works with newer versions

### PR DESCRIPTION
**Pull request by hsanjuan**
Post of shame and comment from dev:

https://discourse.gohugo.io/t/site-built-with-previous-version-wont-build-properly/10420/5

And no, introduced breakage was not documented in 0.32 release notes:

https://gohugo.io/news/0.32-relnotes/

@meiqimichelle mind doing some testing?

We also need to check that jenkins is generating the right result. Probably it's using an older version.

### CODE REVIEW

**Comment by hsanjuan** [comment]
https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fipfs-cluster-website/detail/fix%2Fnew-hugo/1/pipeline

**Comment by hsanjuan** [comment]
https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fipfs-cluster-website/detail/PR-30/1/pipeline

**Comment by meiqimichelle** [comment]
@hsanjuan still not quite right.

Previously, when running our site with latest Hugo, this is what the homepage looked like locally:
screenshot 2018-08-29 12 35 06

And this is what happened when trying to view subpages locally:
screenshot 2018-08-29 12 34 41

On `fix/new-hugo`, the homepage is looking 💯 (yay!) , but the subpages still don't build locally:
screenshot 2018-08-29 12 38 30
We don't get the `404` anymore, but `hugo server` is not finding layouts. We get errors for much of the site like this:
```Unable to locate layout for "page": [documentation/single.en.html.html documentation/single.html.html documentation/single.en.html documentation/single.html _default/single.en.html.html _default/single.html.html _default/single.en.html _default/single.html]```

**Comment by meiqimichelle** [comment]
Hmm, I've been trying to track down the error and it seems like that error / `WARN` always shows up -- even on `master` using Hugo v0.31 to render the pages correctly! Boo.

**Comment by hsanjuan** [comment]
~~Wow, I think they changed this again under my feet because it worked and today I checked (after upgrading hugo again) and again broken!. I have changed the doc layout and things seem fine for me again. Can you try again to double-check?~~

Maybe I had screwed up the template before

**Comment by hsanjuan** [comment]
fixed on #41

**Pull request closed without merging**
