### PR TITLE
More informative title description

### PR DESCRIPTION
**Pull request by kishansagathiya**
With this change, it would look like this
Screenshot from 2019-04-10 10-09-39

### CODE REVIEW

**Comment by hsanjuan** [comment]
Makes me think we can maybe improve the description as a whole...

**Comment by hsanjuan** [comment]
@meiqimichelle @lanzafame @pkafei

**Comment by meiqimichelle** [comment]
There is a [very draft internal doc](https://docs.google.com/document/d/1y_RSNlgZQ1ww84G5MEyT3A5CF0Fx3fOBUPxWOW87Tj0/edit?usp=sharing) iterating on this tag line and other product targeting/descriptions. I agree it should be improved. The start of brainstorm around a better tagline is around page 3 in that doc after the highlighted bit. As it says, though -- we should come to agreement on our initial product direction first so we can write a good description of where to tell people we're headed. I'm hoping to be able to return to that work next week with our various draft docs and the content audit that @pkafei is working on in hand. 

Def. feel free to comment or add to that *extremely* draft doc (more like a place to drop random brainstorms) if anyone has time before next week though!

**Comment by kishansagathiya** [comment]
> Makes me think we can maybe improve the description as a whole...

We should do that. 

Our current description `IPFS Cluster is a stand-alone application and a CLI Client ` provides no interesting information. So, I would say keep the discussion going, but let's not wait for that to merge this PR.

**Comment by hsanjuan** [comment]
> > Makes me think we can maybe improve the description as a whole...
> 
> We should do that.
> 
> Our current description `IPFS Cluster is a stand-alone application and a CLI Client ` provides no interesting information. So, I would say keep the discussion going, but let's not wait for that to merge this PR.

Ok, but please don't make "PINS" a pink thing.

**Comment by kishansagathiya** [comment]
> Ok, but please don't make "PINS" a pink thing.

sure thing

**Review by hsanjuan — APPROVED** [review]

**Pull request merged**
