### PR TITLE
MHz content + typography edits --> `content`

### PR DESCRIPTION
**Pull request by meiqimichelle**
This PR is branched off of @hsanjuan's latest `content`. Some highlights:

- Updated navigation categories, with all content finding a home (including what used to be in guides)
- Typography refinements. All type is a shade thinner, and spacing , sizing, and padding have all been adjusted. I'm not sure if I like the light font weight yet. Also, please let me know how it renders on your machines. It may be unreadable (Windows/Linux/Mac all render light font weights a bit differently).
- CSS animation for hover and links in main content block. Fun!
- Copyedits throughout. I didn't have time to copyedit everything. More later!

Screenshot 2019-07-29 22 56 28

### CODE REVIEW

**Review by hsanjuan — CHANGES_REQUESTED** [review]
I would like to go back to the previous structure with an `administration` section with documentation for the cluster administrator, a usage section with documentation for the cluster user, and a guides section with guides.

This is mixing things in ways that don't help people find the information. It's also mixing guides with reference docs. Guides are a way to get from A to B. A cluster admin does not need to read the guides, but the administration docs. The consensus explanation or the production settings are not written as guides and should be read by administrators.

**Comment by hsanjuan** [comment]
Also, download link missing from the top.

✅ _MHz Update: Fixed._

**Comment by hsanjuan** [comment]
* The CSS changes make the text look too thin, harder to read now. Lists are overly spaced now. I have the feeling it looked better before (the menu had also bigger font). If I remember well, we had set a heavier font after complains because it was hard to read the previous thin one. ✅ _MHz Update: Returned to heavier font weights, and made more adjustments to spacing throughout._
* Dead links in `ipfs-cluster-ctl` page. ✅ _MHz: Done._
* I would delete or hide all legacy stuff: arch doc, release process, dag sharding RFC ❓ _MHz Update: Done. There is one link in the captain's log on 20180125 that talks about the DAG sharding RFC. Where should that link?_
* Unable to link godocs from the menu ❓ _MHz: Where do you want the link -- which menu/section? And what's the url you want to link to?_
* There were `support.md` and `features.md` files at top level. They showed as menu items for me. It seems the menu generation changed and broke this. The new Overview page is empty. It should have the content the main docs page have. Thus, maybe features and roadmap could be simply promoted as top-level sections within docs without being inside an "Overview" section. 🔺 _MHz comment: I fixed the main Overview landing page, there was an already-existing re-direct on another page that was hijacking it. That page can have really high-level stuff -- it can be non-technical, different from the Getting Started landing page. Features can stay under there. There is a new Community section with Support (I renamed 'Support' to 'Getting help, but I'll change it back now. Support is better.)_

I might be persuaded about the "Guides" section here but I need some reasons as now it feels like mixing very unrelated things in a catch-all bag. (Administration+Reference+Guides?). Much of the doc effort was to group things in a way that the users could get to the right doc faster. But now knowing how to manage the pinset is at the same level as understanding the consensus components, which is the exact problem we had before.

API docs should  be in their own section. An API integrator needs to know the API section is all she needs to start.

**Comment by meiqimichelle** [comment]
We need to talk sync about all this otherwise we will be going back and forth in comments for several weeks. Unfortunately, single-threaded notes do not work for content collaboration. Some of these edits came out of conversation with @lanzafame as well, fyi.

**Comment by hsanjuan** [comment]
The download link should take to the installation section in the getting started page. Not be an additional copy of the same thing.

**Comment by hsanjuan** [comment]
Please don't edit comments. I don't get notified.

>     * I would delete or hide all legacy stuff: arch doc, release process, dag sharding RFC question _MHz Update: Done. There is one link in the captain's log on 20180125 that talks about the DAG sharding RFC. Where should that link?_

Here: https://github.com/ipfs/ipfs-cluster-website/blob/f61242c2c99d00dd25ff4c75cd3a40d47ac2cde2/content/documentation/developer/rfcs/dag-sharding-rfc.md

> 
>     * Unable to link godocs from the menu question _MHz: Where do you want the link -- which menu/section? And what's the url you want to link to?_

Go to https://godoc.org/github.com/ipfs/ipfs-cluster. From the "Developer" section (which is now reference I guess). Current docs have it.

> 
>     * There were `support.md` and `features.md` files at top level. They showed as menu items for me. It seems the menu generation changed and broke this. The new Overview page is empty. It should have the content the main docs page have. Thus, maybe features and roadmap could be simply promoted as top-level sections within docs without being inside an "Overview" section. small_red_triangle _MHz comment: I fixed the main Overview landing page, there was an already-existing re-direct on another page that was hijacking it. That page can have really high-level stuff -- it can be non-technical, different from the Getting Started landing page. Features can stay under there. There is a new Community section with Support (I renamed 'Support' to 'Getting help, but I'll change it back now. Support is better.)_

I'm talking about the docs landing page vs the overview landing page. The docs landing page should have the overview. Makes the overview section innecessary, so promote Features and Roadmap to top-level rather than wrapping them in overview.

**Comment by meiqimichelle** [comment]
I am going to merge this branch into the main rewrite/re-architecture branch so we don't get out of sync. I've made a [note](https://github.com/ipfs/ipfs-cluster-website/issues/93#issuecomment-520621644) in the rewrite issue to loop back and address @hsanjuan 's unresolved comment above.

**Pull request merged**
