### PR TITLE
Make Cluster website responsive

### PR DESCRIPTION
**Pull request by meiqimichelle**
For #46 .
- [x] ~Replace table-based layout with Flexbox and CSS Grid~ Used @olizilla 's Tachyons recommendation instead.
- [x] Add design choices that support readability at more screen sizes (at least small - medium - large / mobile - tablet - desktop) _I did a first pass at this, but will do more later_

_Edit May 5_
As pointed out in a comment, this PR ended up doing a lot more than just adding responsive behavior. It ended up being more of a website refactor. Some changes include:
- [x] Refactoring the way that our Hugo templates were implemented so that the homepage, "section" (to use Hugo jargon) pages, and other pages (aka "single" pages to Hugo) could be independently design and updated without unexpected changes in other parts of the site.
- [x] Removed the table-based layout to resolve problems with accessibility, allow responsive design, speed site load time, and allow future modern layout choices.
- [x] Added the Tachiyons css library so that this website uses the same tools as other PL websites (Hugo+Tachyons). This means that more devs across the org can help maintain this site. I then used this library to implement the responsive behaviors that this PR originally was meant to do.

### CODE REVIEW

**Comment by olizilla** [comment]
I love making websites responsive. May I help? One thing to consider is @yusefnapora is setting up the libp2p and filecoin docs sites, using an existing hugo theme. 

see: https://github.com/libp2p/docs

It'd be worth evaluating that theme and possibly re-using it here, or digging into what would need to change in that theme to make it useful here.

**Comment by meiqimichelle** [comment]
Thanks @olizilla ! I'll take a peek. That theme seems very docs-focused, but you are right, it may be easier to modify that theme rather than build from scratch. We shall see, tho! The Cluster site is pretty straightforward, it just needs a bit of time (mine or yours, if you'd like to help) to apply some flexy-ness and grid-ness.

**Comment by meiqimichelle** [comment]
I've started building on [Tachyons](http://tachyons.io/), on the suggestion of @olizilla and @pkafei, as that light toolkit is used on several other PL websites. But check it! We can haz responsive (v1 -- still many details to clean up):

Screenshot 2019-04-29 21 06 36
Screenshot 2019-04-29 21 06 08
Screenshot 2019-04-29 21 06 22

**Comment by meiqimichelle** [comment]
We have a homepage that flows for any screen size! Yays. Next: the other page template (for the sub-pages).
Screenshot_2019-04-30 IPFS CLUSTER

**Comment by meiqimichelle** [comment]
:boom: We have all the rest of the pages now! For example:

Screenshot_2019-05-04 Roadmap

**Comment by meiqimichelle** [comment]
I've removed the WIP -- plz test! The level of test is: is it responsive and not doing anything super strange in any browser? Design improvements will happen next, in another PR.

**Review by hsanjuan — APPROVED** [review]
ok. Super happy that it works slightly better on mobile now.

Not so happy that something like `frontpage-title-text-normal` has turned to `f4 f4-ns fw4 lh-1_3 b measure dib-m lh-copy arctic-teal`, which is super cryptic and needs knowledge in a specific css framework to understand what's going on, where before I could just check an easy CSS rule and change it.

The big logo is not centered on my phone like in the screenshot (we can probably just hide it on narrow screens).  The top menus do flow but are ugly. The footer seems to have got worse (it was ok before). The configuration page tables got worse. Code blocks are not in gray background anymore, font got larger and visually mixes with non-code text (kubernetes user guide for example).

My feeling is that we're killing a small fly (main page and top menu not working on narrow screens) with a big cannon (adopting a full css framework). In my opinion the added maintainability complexity and new issues outweigh the fixed ones, but I'm not a frontend-dev and I suck at design, so go ahead if you think this is the right way to proceed.

**Comment by olizilla** [comment]
I'd be happy to talk about it if you'd be interested in understanding the rationale behind using tachyons for our a bunch of our sites. https://tachyons.io

I have found it makes long term maintenance of a responsive site much less of a chore.

**Comment by meiqimichelle** [comment]
Thanks for the review @hsanjuan! Let's see, here we go!

> Not so happy that something like frontpage-title-text-normal has turned to f4 f4-ns fw4 lh-1_3 b measure dib-m lh-copy arctic-teal, which is super cryptic and needs knowledge in a specific css framework to understand what's going on, where before I could just check an easy CSS rule and change it.

I was also pretty skeptical about using Tachyons at first, but wanted to try it given our front end devs are slowly moving to making that a PL standard. As it turns out, it's *not* a full framework. It's merely a pre-rolled set of utility classes that happen to also make  implementing screen-size-responsiveness very straightforward. I wish the author had chosen more verbose class names, but every css system has drawbacks. It is important to align on one, and accept its particular drawbacks, so that many people across the team can pick up each other's code to prevent bus factor. See also: aligning on Hugo as a templating framework, even with its known quirks. 

As for checking a CSS rule, once I turned my mind to thinking of Tachyons as a mega-utility-class-list, it was just as easy to find the rules; it was the same dev-tools-lookup process as usual. Since we weren't using a standard class name structure before (such as BEM), the old classes weren't particularly straightforward, either, and were not well structured. For example, it was difficult to ensure typography and design rules were reflected *everywhere* because separate classes were made in a one-off way for various parts of the site, rather than using a cascading design system across the site. This made the design difficult to iterate, and the site difficult to maintain.

> The big logo is not centered on my phone like in the screenshot (we can probably just hide it on narrow screens).

...I don't think it's centered in the screenshot? Which one are you talking about? Screenshot, plz!

> The top menus do flow but are ugly. 

Agree. The goal for this PR was to have them be accessible at all (not overflow to right scroll, where many folks won't even see the available options). Next step: design them better. 

> The footer seems to have got worse (it was ok before).

Can you take a screenshot please, and/or describe what you mean? I'm not sure what you mean by "worse". 

> The configuration page tables got worse.

I assume you mean `documentation/configuration/` ? Can you take a screenshot please, and/or describe what you mean? I'm not sure what you mean by "worse". (There were existing problems with the tables on that page that were not addressed in this PR -- such as that after a certain small screen size, the table scrolls right, and doesn't collapse/adjust -- but I'm not sure anything got worse than it already was.)

> Code blocks are not in gray background anymore, font got larger and visually mixes with non-code text (kubernetes user guide for example).

Thanks for finding that! I'll fix that in a commit to this PR for your review in a moment.

> My feeling is that we're killing a small fly (main page and top menu not working on narrow screens) with a big cannon (adopting a full css framework).

This was not a small fly problem. There were many maintainability issues with the old code that this PR refactors. When I set out to make the site responsive, I found other things needed to be fixed as well, as I couldn't fix the responsiveness without also addressing the other issues. Now that you mention it, the title of this PR doesn't accurately reflect the scope anymore -- it should be something more like "website refactor".

For example, the Hugo templates weren't implemented correctly so the templates for the homepage vs the section pages vs the other pages were difficult to change independently (changes on one would cause unexpected changes on others). In addition, the site used tables for layout, which causes problems with accessibility, makes it impossible to adapt to different screen sizes, makes the site load more slowly, and would prevent us from creating modern layouts when re-designing the site in the future.

In short, I couldn't make design improvements until I knew I'd be able to implement them without unreasonable hassle, so future website work was blocked on the refactor in this PR. Most of the time and effort was spent around those refactors, not Tachyons changes. Re: using Tachyons, I wouldn't worry about it too much. It is *not* a framework, it is very lightweight, and very plug-and-play. You can still use any other classes as you see fit, and choose to not use Tachyons without issue. You'll note that even with adding the Tachyons library, the codebase size stayed about the same because of the efficiencies gained in the refactor.

> In my opinion the added maintainability complexity and new issues outweigh the fixed ones, but I'm not a frontend-dev and I suck at design, so go ahead if you think this is the right way to proceed.

This PR puts the code in a much more maintainable place than it was before. However, **I'm happy to wait until we have another rev on design improvements to make sure nothing looks "worse" than it was before before merging to production** (while being careful not to let perfect be the enemy of done). **I do need more info, as noted above, on what "worse" means though!** In the meantime, I can do another design improvement rev to include in this PR.

**Comment by meiqimichelle** [comment]
Centered header at small+medium screen sizes ✅ 
Screenshot 2019-05-05 22 49 51

Centered footer at small+medium screen sizes ✅
Screenshot 2019-05-05 22 41 41

Code display should be back to where it is in our current live site ✅

**Comment by meiqimichelle** [comment]
(Also -- I checked with @cwaring -- his little banner will not show up locally, but it will be all good when pushed live)

**Comment by meiqimichelle** [comment]
@hsanjuan @pkafei @olizilla @lanzafame can you give this a look (or one more look) to see if there are any big design regressions, or bugs? (Plz screenshot!)

**Comment by pkafei** [comment]
LGTM

**Pull request merged**
