### PR TITLE
Adds a few words on using the correct Hugo version

### PR DESCRIPTION
**Pull request by meiqimichelle**

### CODE REVIEW

**Comment by hsanjuan** [comment]
oh, we should just make it work on latest hugo

**Comment by meiqimichelle** [comment]
Should. But not sure when we'll have time. Until then -- is this a good stop-gap?

**Comment by hsanjuan** [comment]
No, I'll fix it next week. It should not be horribly difficult.

**Comment by meiqimichelle** [comment]
Overtaken by #30 . Closing.

**Pull request closed without merging**
